# Generated by Django 2.0.6 on 2021-08-27 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cryptobitsapp', '0002_auto_20200629_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBasicInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True)),
                ('postal_code', models.CharField(default='00000', max_length=70)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=35)),
                ('amount_available', models.DecimalField(decimal_places=2, max_digits=35)),
                ('amount_withdrawable', models.DecimalField(decimal_places=2, max_digits=35)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
