# Generated by Django 2.0.6 on 2021-08-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0003_userbasicinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbasicinformation',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True),
        ),
    ]
