# Generated by Django 2.0.6 on 2021-08-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0004_auto_20210826_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=5000)),
                ('notice_type', models.CharField(choices=[('SF', 'safe'), ('WR', 'warning'), ('NE', 'Neutral'), ('NN', 'None')], default='NN', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='userbasicinformation',
            name='pro_verified',
            field=models.BooleanField(default=False),
        ),
    ]
