# Generated by Django 2.0.6 on 2021-08-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0005_auto_20210826_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
