# Generated by Django 2.0.6 on 2021-08-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0006_companydetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='email',
            field=models.EmailField(default='NONE', max_length=50),
        ),
    ]
