# Generated by Django 2.0.6 on 2021-08-31 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cryptobitsapp', '0007_companydetail_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eth', models.CharField(max_length=150)),
                ('btc', models.CharField(max_length=150)),
                ('bnb', models.CharField(max_length=150)),
                ('dodge', models.CharField(max_length=150)),
                ('Xrp', models.CharField(max_length=150)),
                ('bch', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
