# Generated by Django 2.0.6 on 2021-08-31 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0008_walletaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletaddress',
            old_name='Xrp',
            new_name='xrp',
        ),
    ]
