# Generated by Django 2.0.6 on 2021-08-31 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0010_withdrawaltransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawaltransaction',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=35),
            preserve_default=False,
        ),
    ]
