# Generated by Django 2.0.6 on 2021-09-01 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0011_withdrawaltransaction_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawaltransaction',
            name='date_completed',
        ),
    ]
