# Generated by Django 2.0.6 on 2021-09-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0012_remove_withdrawaltransaction_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='minimum_investment',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=35),
            preserve_default=False,
        ),
    ]
