# Generated by Django 2.0.6 on 2021-09-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0013_companydetail_minimum_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='name',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
