# Generated by Django 2.0.6 on 2021-09-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0014_companydetail_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='minimum_withdraw',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=35),
            preserve_default=False,
        ),
    ]
