# Generated by Django 2.0.6 on 2021-09-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0015_companydetail_minimum_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydetail',
            name='maximum_investment',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydetail',
            name='maximum_withdraw',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=35),
            preserve_default=False,
        ),
    ]
