# Generated by Django 2.0.6 on 2021-09-01 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0017_acceptedcoins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetail',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='maximum_investment',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='maximum_withdraw',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='minimum_investment',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='minimum_withdraw',
        ),
    ]
