# Generated by Django 2.0.6 on 2021-09-01 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0018_auto_20210831_2013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcceptedCoins',
            new_name='AcceptedCoin',
        ),
    ]
