# Generated by Django 2.0.6 on 2021-09-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0019_auto_20210831_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedcoin',
            name='code',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
