# Generated by Django 2.0.6 on 2021-09-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0020_acceptedcoin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedcoin',
            name='time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
