# Generated by Django 2.0.6 on 2021-09-01 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0022_auto_20210901_0433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawaltransaction',
            old_name='currency',
            new_name='currency_coin',
        ),
    ]
