# Generated by Django 2.0.6 on 2021-09-01 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0023_auto_20210901_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposittransaction',
            name='currency',
        ),
        migrations.AddField(
            model_name='deposittransaction',
            name='currency_coin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Accepted_Coin_deposit', to='cryptobitsapp.AcceptedCoin'),
        ),
        migrations.AddField(
            model_name='deposittransaction',
            name='uuid',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawaltransaction',
            name='uuid',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='withdrawaltransaction',
            name='currency_coin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Accepted_Coin_withdraw', to='cryptobitsapp.AcceptedCoin'),
        ),
    ]
