# Generated by Django 2.0.6 on 2021-09-01 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0024_auto_20210901_0503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptedcoin',
            old_name='maximum_investment',
            new_name='maximum_deposit',
        ),
        migrations.RenameField(
            model_name='acceptedcoin',
            old_name='minimum_investment',
            new_name='minimum_deposit',
        ),
    ]
