# Generated by Django 2.0.6 on 2021-09-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0025_auto_20210901_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposittransaction',
            name='receiver_address',
        ),
    ]
