# Generated by Django 2.0.6 on 2021-09-02 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0026_remove_deposittransaction_receiver_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawaltransaction',
            name='currency_coin',
        ),
    ]
