# Generated by Django 2.0.6 on 2021-09-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0028_auto_20210901_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposittransaction',
            name='coin_code',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
