# Generated by Django 2.0.6 on 2021-09-02 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0029_deposittransaction_coin_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawaltransaction',
            name='address',
        ),
    ]
