# Generated by Django 2.0.6 on 2021-09-03 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cryptobitsapp', '0030_remove_withdrawaltransaction_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=70)),
                ('account_name', models.CharField(max_length=70)),
                ('account_number', models.CharField(max_length=70)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
