# Generated by Django 3.2.7 on 2021-09-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0031_bankinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedcoin',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='acceptedcoin',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='deposittransaction',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='bch',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='bnb',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='btc',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='dodge',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='eth',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='xrp',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
