# Generated by Django 3.2.7 on 2021-09-07 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cryptobitsapp', '0032_auto_20210906_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefiCoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('coin', models.CharField(max_length=5)),
                ('code', models.CharField(max_length=5)),
                ('dollar_value', models.DecimalField(decimal_places=2, max_digits=35)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('short_interest_rate', models.DecimalField(decimal_places=2, max_digits=35)),
                ('available', models.BooleanField(default=True)),
                ('med_interest_rate', models.DecimalField(decimal_places=2, max_digits=35)),
                ('long_interest_rate', models.DecimalField(decimal_places=2, max_digits=35)),
                ('minimum_lock_amount', models.DecimalField(decimal_places=10, max_digits=35)),
                ('maximum_lock_amount', models.DecimalField(decimal_places=10, max_digits=35)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=35)),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StakingStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('available', models.BooleanField(default=True)),
                ('dollar_value', models.DecimalField(decimal_places=2, max_digits=35)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('short_interest_rate', models.DecimalField(decimal_places=2, max_digits=35)),
                ('med_interest_rate', models.DecimalField(decimal_places=2, max_digits=35)),
                ('long_interest_rate', models.DecimalField(decimal_places=2, max_digits=35)),
                ('minimum_lock_amount', models.DecimalField(decimal_places=10, max_digits=35)),
                ('maximum_lock_amount', models.DecimalField(decimal_places=10, max_digits=35)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=35)),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='status',
            field=models.CharField(choices=[('SUB', 'submitted'), ('APV', 'approved'), ('DCL', 'declined')], default='SUB', max_length=3),
        ),
        migrations.AlterField(
            model_name='withdrawaltransaction',
            name='status',
            field=models.CharField(choices=[('SUB', 'submitted'), ('APV', 'approved'), ('DCL', 'declined')], default='SUB', max_length=3),
        ),
        migrations.CreateModel(
            name='UserStockStaking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=35)),
                ('stake_date', models.DateTimeField(auto_now_add=True)),
                ('value_date', models.DateTimeField(blank=True, null=True)),
                ('interest_end_date', models.DateTimeField(blank=True, null=True)),
                ('redemption_date', models.DateTimeField(blank=True, null=True)),
                ('interest_period', models.IntegerField()),
                ('redemption_period', models.IntegerField()),
                ('status', models.CharField(choices=[('SUB', 'submitted'), ('APV', 'approved'), ('DCL', 'declined')], default='SUB', max_length=3)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Staking_stock', to='cryptobitsapp.stakingstock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDefiStaking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=35)),
                ('interest_period', models.IntegerField()),
                ('redemption_period', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=35)),
                ('status', models.CharField(choices=[('SUB', 'submitted'), ('APV', 'approved'), ('DCL', 'declined')], default='SUB', max_length=3)),
                ('coin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DefiCoin', to='cryptobitsapp.deficoin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
