# Generated by Django 3.2.7 on 2021-09-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0034_remove_userbasicinformation_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbasicinformation',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True, default="2021-01-05"),
            preserve_default=False,
        ),
    ]
