# Generated by Django 3.2.7 on 2021-09-07 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0036_userbasicinformation_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbasicinformation',
            name='date_of_birth',
        ),
    ]
