# Generated by Django 3.2.7 on 2021-09-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0038_rename_birth_date_userbasicinformation_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedcoin',
            name='network',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
