# Generated by Django 3.2.7 on 2021-09-12 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cryptobitsapp', '0039_acceptedcoin_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=35)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Accepted_Coin', to='cryptobitsapp.acceptedcoin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
