# Generated by Django 3.2.7 on 2021-09-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0040_userwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedcoin',
            name='dollar_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='balance',
            field=models.DecimalField(decimal_places=9, max_digits=35),
        ),
    ]
