# Generated by Django 3.2.7 on 2021-09-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0041_auto_20210912_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedcoin',
            name='dollar_value',
            field=models.DecimalField(decimal_places=5, max_digits=35),
        ),
        migrations.AlterField(
            model_name='deficoin',
            name='dollar_value',
            field=models.DecimalField(decimal_places=5, max_digits=35),
        ),
        migrations.AlterField(
            model_name='stakingstock',
            name='dollar_value',
            field=models.DecimalField(decimal_places=5, max_digits=35),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='balance',
            field=models.DecimalField(decimal_places=5, max_digits=35),
        ),
    ]
