# Generated by Django 3.2.7 on 2021-09-21 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cryptobitsapp', '0042_auto_20210912_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbasicinformation',
            name='address',
            field=models.CharField(default='no address', max_length=250),
        ),
        migrations.AlterField(
            model_name='acceptedcoin',
            name='dollar_value',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.CreateModel(
            name='BasicVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
