# Generated by Django 3.2.7 on 2021-09-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0044_delete_basicverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbasicinformation',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='userbasicinformation',
            name='city',
            field=models.CharField(default='new york', max_length=70),
        ),
    ]
