# Generated by Django 3.2.7 on 2021-09-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0045_auto_20210921_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbasicinformation',
            name='postal_code',
            field=models.CharField(default='09876', max_length=70),
        ),
    ]
