# Generated by Django 3.2.7 on 2021-09-26 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cryptobitsapp', '0046_userbasicinformation_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deficoin',
            name='maximum_lock_amount',
            field=models.DecimalField(decimal_places=6, max_digits=35),
        ),
        migrations.AlterField(
            model_name='deficoin',
            name='minimum_lock_amount',
            field=models.DecimalField(decimal_places=6, max_digits=35),
        ),
        migrations.AlterField(
            model_name='stakingstock',
            name='maximum_lock_amount',
            field=models.DecimalField(decimal_places=6, max_digits=35),
        ),
        migrations.AlterField(
            model_name='stakingstock',
            name='minimum_lock_amount',
            field=models.DecimalField(decimal_places=6, max_digits=35),
        ),
        migrations.CreateModel(
            name='UserIntermediateInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_id', models.ImageField(blank=True, null=True, upload_to='')),
                ('gov_id_front', models.ImageField(blank=True, null=True, upload_to='')),
                ('gov_id_back', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAdvanceInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_of_address', models.ImageField(blank=True, null=True, upload_to='')),
                ('SSN', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
