# Generated by Django 3.2.7 on 2021-09-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0047_auto_20210926_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintermediateinformation',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
