# Generated by Django 3.2.7 on 2021-09-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0048_userintermediateinformation_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradvanceinformation',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
