# Generated by Django 3.2.7 on 2021-09-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0049_useradvanceinformation_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdefistaking',
            name='farming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userstockstaking',
            name='farming',
            field=models.BooleanField(default=False),
        ),
    ]
