# Generated by Django 3.2.7 on 2021-09-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0050_auto_20210928_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstockstaking',
            name='rate_per_hr',
            field=models.IntegerField(default=0),
        ),
    ]
