# Generated by Django 3.2.7 on 2021-09-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0051_userstockstaking_rate_per_hr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstockstaking',
            old_name='rate_per_hr',
            new_name='rate_per_hour',
        ),
        migrations.AddField(
            model_name='userdefistaking',
            name='rate_per_hour',
            field=models.IntegerField(default=0),
        ),
    ]
