# Generated by Django 3.2.7 on 2021-09-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0052_auto_20210928_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdefistaking',
            name='timer',
            field=models.CharField(default='time', max_length=500),
        ),
        migrations.AddField(
            model_name='userstockstaking',
            name='timer',
            field=models.CharField(default='time', max_length=500),
        ),
    ]
