# Generated by Django 3.2.7 on 2021-09-29 09:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0053_auto_20210929_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstockstaking',
            name='interest_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 29, 9, 26, 33, 302739, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='stake_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 29, 9, 26, 33, 302739, tzinfo=utc), null=True),
        ),
    ]
