# Generated by Django 3.2.7 on 2021-09-29 10:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0054_auto_20210929_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstockstaking',
            name='last_credit_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 29, 10, 10, 7, 795697, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='interest_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 29, 10, 10, 7, 795697, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='stake_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 29, 10, 10, 7, 795697, tzinfo=utc), null=True),
        ),
    ]
