# Generated by Django 3.2.7 on 2021-09-29 18:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0055_auto_20210929_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstockstaking',
            name='redemption_date',
        ),
        migrations.RemoveField(
            model_name='userstockstaking',
            name='redemption_period',
        ),
        migrations.RemoveField(
            model_name='userstockstaking',
            name='timer',
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='interest_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 29, 18, 13, 27, 222383, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='interest_period',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='last_credit_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 29, 18, 13, 27, 222383, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='quantity',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=35),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='stake_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 29, 18, 13, 27, 222383, tzinfo=utc), null=True),
        ),
    ]
