# Generated by Django 3.2.7 on 2021-09-29 21:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0056_auto_20210929_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstockstaking',
            name='farm_quantity',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=35),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='interest_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 29, 21, 30, 42, 212737, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='last_credit_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 29, 21, 30, 42, 212737, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='stake_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 29, 21, 30, 42, 212737, tzinfo=utc), null=True),
        ),
    ]
