# Generated by Django 3.2.7 on 2021-10-01 15:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0060_auto_20211001_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdefistaking',
            name='timer',
        ),
        migrations.AlterField(
            model_name='userdefistaking',
            name='interest_period',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdefistaking',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=35),
        ),
        migrations.AlterField(
            model_name='userdefistaking',
            name='last_credit_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 1, 15, 6, 20, 961960, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userdefistaking',
            name='quantity',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=35),
        ),
        migrations.AlterField(
            model_name='userdefistaking',
            name='redemption_period',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='interest_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 1, 15, 6, 20, 960960, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='last_credit_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 1, 15, 6, 20, 960960, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='stake_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 1, 15, 6, 20, 960960, tzinfo=utc), null=True),
        ),
    ]
