# Generated by Django 3.2.7 on 2021-10-03 05:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0061_auto_20211001_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedcoin',
            name='api_id',
            field=models.CharField(default='api-trace-id', max_length=20),
        ),
        migrations.AddField(
            model_name='deficoin',
            name='api_id',
            field=models.CharField(default='api-trace-id', max_length=20),
        ),
        migrations.AddField(
            model_name='stakingstock',
            name='api_id',
            field=models.CharField(default='api-trace-id', max_length=20),
        ),
        migrations.AlterField(
            model_name='userbasicinformation',
            name='city',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='userbasicinformation',
            name='postal_code',
            field=models.CharField(default='0000', max_length=70),
        ),
        migrations.AlterField(
            model_name='userdefistaking',
            name='last_credit_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 3, 5, 29, 52, 616788, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='interest_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 3, 5, 29, 52, 616788, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='last_credit_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 3, 5, 29, 52, 616788, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='stake_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 3, 5, 29, 52, 616788, tzinfo=utc), null=True),
        ),
    ]
