# Generated by Django 3.2.7 on 2021-10-03 05:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0062_auto_20211003_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbasicinformation',
            name='city',
            field=models.CharField(default='not added', max_length=70),
        ),
        migrations.AlterField(
            model_name='userdefistaking',
            name='last_credit_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 3, 5, 31, 30, 275799, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='interest_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 3, 5, 31, 30, 273798, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='last_credit_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 3, 5, 31, 30, 273798, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='stake_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 3, 5, 31, 30, 273798, tzinfo=utc), null=True),
        ),
    ]
