# Generated by Django 3.2.7 on 2021-10-05 11:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0066_auto_20211004_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbasicinformation',
            name='moblie',
            field=models.CharField(default='NO MOBILE', max_length=15),
        ),
        migrations.AlterField(
            model_name='userdefistaking',
            name='interest_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 5, 11, 37, 19, 518951, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userdefistaking',
            name='last_credit_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 5, 11, 37, 19, 515944, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userdefistaking',
            name='stake_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 5, 11, 37, 19, 515944, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='interest_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 5, 11, 37, 19, 513943, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='last_credit_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 5, 11, 37, 19, 513943, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='stake_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 5, 11, 37, 19, 513943, tzinfo=utc), null=True),
        ),
    ]
