# Generated by Django 3.2.7 on 2022-10-14 07:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0068_auto_20211005_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbasicinformation',
            name='title',
            field=models.CharField(default='NONE', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdefistaking',
            name='interest_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 14, 7, 6, 38, 605548, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userdefistaking',
            name='last_credit_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 14, 7, 6, 38, 604548, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userdefistaking',
            name='stake_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 14, 7, 6, 38, 605548, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='interest_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 14, 7, 6, 38, 604548, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='last_credit_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 14, 7, 6, 38, 604548, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='stake_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 14, 7, 6, 38, 604548, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='balance',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=35),
        ),
    ]
