# Generated by Django 3.2.7 on 2023-02-23 12:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cryptobitsapp', '0070_auto_20221018_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdefistaking',
            name='interest_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 23, 12, 47, 35, 785809, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userdefistaking',
            name='last_credit_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 23, 12, 47, 35, 785809, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userdefistaking',
            name='stake_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 23, 12, 47, 35, 785809, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='interest_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 23, 12, 47, 35, 785310, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='last_credit_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 23, 12, 47, 35, 785310, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='stake_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 23, 12, 47, 35, 785310, tzinfo=utc), null=True),
        ),
        migrations.CreateModel(
            name='UserAccountInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_id', models.ImageField(blank=True, null=True, upload_to='')),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='')),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
