# Generated by Django 3.2.7 on 2023-02-23 15:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cryptobitsapp', '0073_auto_20230223_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdefistaking',
            name='interest_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 23, 15, 0, 6, 754247, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userdefistaking',
            name='last_credit_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 23, 15, 0, 6, 754247, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userdefistaking',
            name='stake_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 23, 15, 0, 6, 754247, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='interest_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 23, 15, 0, 6, 753249, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='last_credit_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 23, 15, 0, 6, 753249, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userstockstaking',
            name='stake_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 23, 15, 0, 6, 753249, tzinfo=utc), null=True),
        ),
    ]
